version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/estuary-agent # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: estuary-agent-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: estuary-agent-{{ checksum "pom.xml" }}
      - run:
          command: wget https://estuary-agent-go.s3.eu-central-1.amazonaws.com/4.1.0/runcmd-linux
          name: "download runcmd-linux"
      - run:
          command: mv runcmd-linux  runcmd
          name: "rename runcmd-linux"
      - run:
          command: chmod +x runcmd
          name: "chmod +x runcmd-linux"
      - run:
          command: printenv
          name: "print env vars"
      - run:
          command: mvn clean package # run the actual tests
          environment:
            COMMAND_TIMEOUT: 3
          name: "clean package"
      - run:
          command: sudo apt-get update
          name: "apt-get update"
      - run:
          command: sudo apt-get install gnupg2
          name: "install gnupg2"
      #      - run:
      #          command: export GPG_KEYNAME=$(gpg2 --list-keys | head -4 | tail -1 |  sed 's/^\s+//g') && mvn -s settings.xml clean deploy -DskipTests=true
      #          name: "deploy"

      # -> for new gpg2 key: export GNUPGHOME="$(mktemp -d)" && export GPG_TTY=$(tty) && gpg --batch --generate-key .circleci/gpgtemplate &&

      - store_artifacts: # store the jar as an artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/agent-4.1.0-SNAPSHOT-exec.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
